### ISSUE TITLE
Unable to reproduce example due to plotting error

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#2]
I have attempted to reproduce the example provided for the Colville using a binary mask of the Yukon (can attach if necessary). When I reach yukon.plot('network'), having run the example code modified for the Yukon, I get an error about axis not being found. Code and error reproduced below. This occurred both in a modified jupyter notebook and in a spyder environment.

```python
from rivgraph.rivgraph import delta
import matplotlib.pyplot as plt
import os

# Define the path to the georeferenced binary image.
mask_path = r"C:\Users\Lawrence Vulis\Documents\deltas\r_work\UTM\Yukon\compoun_binary.tif"

# Results will be saved with this name
name = 'Yukon' 

# A folder called Yukon will be created within this path for storing outputs
results_folder = r"C:\Users\Lawrence Vulis\Documents\deltas\RivGraph-master\LV_extraction\Results" 

# Boot up the delta class! We set verbose=True to see progress of processing.
yukon = delta(name, mask_path, results_folder=results_folder, verbose=True) 

# The mask has been re-binarized and stored as an attribute of yukon:
plt.imshow(yukon.Imask)


# Simply use the skeletonize() method.
yukon.skeletonize()

# After running, yukon has a new attribute: Iskel. Let's take a look.
plt.imshow(yukon.Iskel)


# The skeleton is hard to see; perhaps we'd like to look at it closer?
# One option is to save it as a geotiff and pull it up in a GIS (like QGIS).
# We use the write_geotiff() method with the "skeleton" option.
yukon.to_geotiff('skeleton')



# Simply use the compute_network() method.
yukon.compute_network()


# Now we can see that the "links" and "nodes" dictionaries have been added as yukon attributes:
links = yukon.links
nodes = yukon.nodes
print('links: {}'.format(links.keys()))
print('nodes: {}'.format(nodes.keys()))


yukon.plot('network')
```

```python
yukon.plot('network')
Traceback (most recent call last):

  File "<ipython-input-7-23d8c36cc499>", line 1, in <module>
    yukon.plot('network')

  File "C:\Anaconda3\envs\geo_py37\lib\site-packages\rivgraph-0.2-py3.7.egg\rivgraph\rivgraph.py", line 263, in plot
    f = lnu.plot_network(self.links, self.nodes, self.Imask, self.name, axis=axis)

TypeError: plot_network() got an unexpected keyword argument 'axis'
```

**Comment by jonschwenk** [comment]
Thanks @Lvulis for bringing this up. The issue was caused by an old version of ln_utils; I've updated all the scripts in the repo now and tested to ensure this issue is resolved. Please grab the latest codes and let me know if you still have problems.
